# Generated by Django 2.2.16 on 2023-05-09 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_created_models_teacher_studentgroup_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='tasks.Student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='tasks.Task')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='tasks',
            field=models.ManyToManyField(through='tasks.Mark', to='tasks.Task'),
        ),
    ]
